services:
  rabbit-provider:
    build:
      context: .
      dockerfile: ./apps/rabbit-provider/Dockerfile
      target: development
    command: npm run start:dev rabbit-provider
    env_file:
      - ./apps/rabbit-provider/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
  rabbit-consumer:
    build:
      context: .
      dockerfile: ./apps/rabbit-consumer/Dockerfile
      target: development
    command: npm run start:dev rabbit-consumer
    env_file:
      - ./apps/rabbit-consumer/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'

